import type { Metadata } from 'next';
import './globals.css';
import { Nunito } from 'next/font/google';
import { ReactNode } from 'react';
import { Header } from '@/components/header';
import { SidebarInset, SidebarProvider } from '@/components/ui/sidebar';
import { CatalogSidebar } from '@/components/catalog-sidebar';
import { CustomSidebarTrigger } from '@/components/ui/custom-sidebar-trigger';
import { CartSidebar } from '@/components/cart-sidebar';
import { Toaster } from '@/components/ui/sonner';
import { getBasketItems } from '@/api/basket';
import { getCookie } from '@/lib/cookie';
import { jwtDecode } from 'jwt-decode';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const nunito = Nunito({
  subsets: ['cyrillic', 'latin'],
  display: 'swap',
  preload: true,
});

export default async function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  const getBasket = async () => {
    const token = await getCookie('token');
    if (token) {
      const decodedToken = jwtDecode(token?.value);
      const response = await getBasketItems(decodedToken?.id);
      return { basketId: decodedToken?.id, response };
    }
  };

  const basketResponse = await getBasket();

  return (
    <html lang='ru'>
      <body className={`antialiased ${nunito.className} bg-blue`}>
        <Header />
        <SidebarProvider defaultOpen>
          <CatalogSidebar />
          <CustomSidebarTrigger className='fixed right-6 top-7 z-10 md:hidden' />
          <SidebarInset>
            <div className='flex-1 rounded-2xl bg-white p-4 max-md:mx-2.5 max-md:mt-2.5 max-md:max-w-full md:max-w-[calc(100vw-29rem-8px)]'>
              {children}
            </div>
            <CartSidebar
              basketId={basketResponse?.basketId}
              basket={basketResponse?.response.data}
            />
          </SidebarInset>
        </SidebarProvider>
        <Toaster />
      </body>
    </html>
  );
}
