import type { Metadata } from 'next';
import './globals.css';
import { Nunito } from 'next/font/google';
import { ReactNode } from 'react';
import { Header } from '@/components/header';
import { Footer } from '@/components/footer';
import { SidebarProvider } from '@/components/ui/sidebar';
import { AppSidebar } from '@/components/app-sidebar';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const nunito = Nunito({
  subsets: ['cyrillic', 'latin'],
  display: 'swap',
  preload: true,
});

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang='ru'>
      <body
        className={`antialiased ${nunito.className} overflow-x-hidden bg-background`}
      >
        <div className='bg-background-secondary pointer-events-none fixed -right-[600px] -top-[230px] z-[-1] h-[1500px] w-[600px] -rotate-[30deg] xl:-right-[400px]' />
        <SidebarProvider defaultOpen>
          <AppSidebar />
          <main className='flex min-h-dvh w-full flex-col'>
            <Header />
            {children}
            <Footer />
          </main>
        </SidebarProvider>
      </body>
    </html>
  );
}
