import type { Metadata } from 'next';
import './globals.css';
import { Nunito } from 'next/font/google';
import { ReactNode } from 'react';
import { Header } from '@/components/header';
import { SidebarInset, SidebarProvider } from '@/components/ui/sidebar';
import { CatalogSidebar } from '@/components/catalog-sidebar';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const nunito = Nunito({
  subsets: ['cyrillic', 'latin'],
  display: 'swap',
  preload: true,
});

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang='ru'>
      <body className={`antialiased ${nunito.className} bg-blue`}>
        <Header />
        <SidebarProvider defaultOpen>
          <CatalogSidebar />
          <SidebarInset>
            <main className='z-[2] my-16 max-lg:max-w-[calc(100vw-14.25rem-16px)] max-md:max-w-full'>
              {children}
            </main>
          </SidebarInset>
        </SidebarProvider>
      </body>
    </html>
  );
}
